# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  run:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v1
        with:
           repository: Ini-effectual/my-demo
           
      - name: Install git 
        run: |
          sudo apt-get install -y git
          git --version
          echo "Path is ... $PATH"
           
      - name: run git commands
        run: |
           git config --global user.name 'ini-effectual'
           git config --global user.email 'ini.inyang@effectual.com'
           git clone https://github.com/Ini-effectual/my-demo.git
           git clone --mirror https://github.com/Ini-effectual/my-test.git
