# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  run:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v1
        with:
           repository: Ini-effectual/my-demo
           
      - name: Install git 
        run: |
          sudo apt-get install -y git
          git --version
          echo "Path is ... $PATH"
           
     # - name: run git commands
     # - run:  echo "$PRIVATE_KEY" 
      #  shell: bash
      #  env:
      #    SSH_KEY: ${{secrets.PRIVATE_KEY}} 
    
      - run: |
           git config --global user.name 'git@github.com'
           git config --global user.email 'ini.inyang@effectual.com'
           sudo git clone git@github.com:Ini-effectual/my-demo.git
           sudo git clone --mirror git@github.com:Ini-effectual/my-test.git
