# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  run:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Install git 
        env: 
            PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
        run: |
          sudo apt-get install -y git
          git --version
          echo "Path is ... $PATH"
      - run: | 
           mkdir ~/.ssh
           chmod 600 id_rsa
           mv id_rsa ~/.ssh/
           mv config ~/.ssh/
           echo $PRIVATE_KEY
           git config --global user.name 'Ini-effectual'
           git config --global user.email 'ini.inyang@effectual.com'
           # https://docs.github.com/en/repositories/creating-and-managing-repositories/duplicating-a-repository#mirroring-a-repository-in-another-location
           git clone --mirror git@github.com:Ini-effectual/my-demo.git
           git fetch --unshallow
           git remote set-url --push origin git@github.com:Ini-effectual/my-test.git
           git fetch -p origin
           git push --mirror
