# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  run:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
           
      - name: Install git 
        run: |
          sudo apt-get install -y git
          git --version
          echo "Path is ... $PATH"
    
      - run: |
           git config --global user.name 'Ini-effectual'
           git config --global user.email 'ini.inyang@effectual.com'
           #sudo git clone git@github.com:Ini-effectual/my-demo.git
           sudo git clone --mirror git@github.com:Ini-effectual/my-test.git
