# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  run:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
           
      - name: Install git 
        run: |
          sudo apt-get install -y git
          git --version
          echo "Path is ... $PATH"
    
      - run: | 
           mkdir ~/.ssh
           chmod 600 id_rsa
           mv id_rsa ~/.ssh/
           cat ~/.ssh/id_rsa
           mv config ~/.ssh/
           printenv
           echo $PRIVATE_KEY >> test
           cat test
           git config --global user.name 'Ini-effectual'
           git config --global user.email 'ini.inyang@effectual.com'
           #cat ~/.ssh/config
           git clone --mirror git@github.com:Ini-effectual/my-test.git
           cat test
           env: 
            PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
            shell: bash
